### ISSUE TITLE
Redirect instead of popup

### ISSUE THREAD

**Issue by garmoned** [ibm-cloud-security/appid-clientsdk-js#62]
Is there a way to avoid having a popup window. It is very inconvenient and makes signing in multiple times very cumbersome.

**Comment by esmiralha** [comment]
Please, pay some attention to this issue...

**Comment by Micha228** [comment]
Im also interested in this.

**Comment by vladimiratanasov** [comment]
Unfortunately, in an SPA application, one without a backend, that would be impossible. To implement the authorization flow without a popup, you will have to navigate away from your SPA page, which will mean losing the application state. You can read more about the PKCE flow used in the client SDK [here](https://cloud.ibm.com/docs/appid?topic=appid-single-page&interface=ui).

If you wish to avoid presenting a popup to the user, you can look into implementing a backend for your application, by using our serverside SDK (or any other SDK that supports oAuth authorization flows). The documentation can be found [here](https://cloud.ibm.com/docs/appid?topic=appid-web-apps&interface=ui)
